apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: springbootdemo
  name: springbootdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbootdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: springbootdemo
    spec:
      containers:
      - image: manikvashisht/samplespringbootapplication:1.0
        name: samplespringbootapplication
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springbootdemo
  name: springbootdemo
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springbootdemo
  type: ClusterIP
status:
  loadBalancer: {}
