spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: API-SERVICE
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
  rabbitmq:
    address: localhost:5672
  datasource:
    password: password
    username: root
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/testDB
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: 'true'
    fetch-registry: 'true'
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: '8090'
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
